spring:
  application:
    name: spring-cloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hzihui/config.git
          search-paths: application
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka/
server:
  port: 6000

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
